module.exports = {
    "idSistema": 1,
    "ativo": true,
    "valido": true,
    "tipoConsulta": 0,
    "consultaPaginada": false,
    "baseDados": -1,
    "contratos": [
      {
        "id": 2,
        "nome": "TERESINA",
        "descricao": "TERESINA",
        "estimativaValorMensal": 0,
        "estimativaValorTotal": 0,
        "dataInicial": 1559098800000,
        "dataFinal": 1559098800000,
        "latitude": "-4.904277731432103",
        "longitude": "-42.60179534827665",
        "zoom": 10,
        "ativo": true,
        "consolidarDados": true,
        "horaInicioConsolidacao": 2,
        "ipServerCentralProcess": null,
        "qtdDiasVencRegNaoMetro": 40,
        "qtdDiasVencAfericao": 40,
        "tempoVerifAlerta": 60,
        "envioSisgit": true,
        "tempoEnvioInfracaoSisgit": 60000,
        "tempoEnvioEventoSisgit": 60000,
        "timeOutEnvioSisgit": 120,
        "envioVideoSisgit": false,
        "urlWsSisgit": "http://172.10.1.165:8080/sisgit-ws/service?wsdl",
        "qtdEventosEnvioSisgit": 0,
        "qtdInfracoesEnvioSisgit": 100,
        "qtdDiasEnvioSisgit": 30,
        "dtInicioEnvioSisgit": "01/01/2017 08:40:09",
        "envioEventoValidoSisgit": true,
        "envioSpia": true,
        "envioAlerta": true,
        "envioAtAfv": false,
        "envioAtsmd2i": false,
        "envioLapisco": false,
        "urlEnvioLapisco": null,
        "urlEnvioAtsmd2i": null,
        "envioBiAtlanta": false,
        "urlEnvioBiAtlanta": null,
        "chaveEnvioBiAtlanta": null,
        "chaveWsAtsmd2i": null,
        "tempoEnvioSpia": 20000,
        "tempoConsultaSpia": 10,
        "tempoEnvioLapisco": 20000,
        "qtdEventosConsultaSpia": 400,
        "urlWsSpia": "https://wsocrspia.prf.gov.br/wsocrspia/pi",
        "usuarioSpia": "LABOR",
        "senhaSpia": "C08558B3E10008EFADAAA42839C2D0",
        "layoutSpia": "ATLLLLLF",
        "tempoEnvioInfracaoChegada": 1,
        "urlBi": "https://app.powerbi.com/view?r=eyJrIjoiODc4OWM2ZjQtODFmOC00NWVlLWI4NTMtMWEzNmQ1ODQ4NmFmIiwidCI6ImRhOWYxNTBmLWFjZDktNGRkYi04YjI1LTdiNGE2NzYzMjRiNSJ9&pageName=ReportSection70e00a36390c20002db1",
        "urlBiSeguranca": null,
        "urlBiCad": null,
        "situacao": 2,
        "nmCliente": "-",
        "imgLogoCliente": null,
        "pathLogo": "/dados/dataserver/anexos//contrato/2/2.png",
        "qtdDiasVencLicenca": 30,
        "tempoMaxVerifOffMin": 60,
        "tempoMaxVerifFluxoMin": 30,
        "tempoMaxVerifInfraMin": 60,
        "qtdDiasGeracaoLicenca": 365,
        "exportaArquivoFluxo": true,
        "envioArquivoFluxoFtp": false,
        "abrangencia": 2,
        "uf": "PI   ",
        "municipio": "Teresina",
        "gerarArquivoAnttAtivo": false,
        "custoMedioFaixa": 100,
        "codigosEnvioInfracaoAtsmsd2i": null,
        "qtdDiasEnvioAtsmd2i": 1,
        "equipamentos": null,
        "anexos": null
      }
    ],
    "idContrato": 2,
    "numerosSerieEquipamento": [
      "ATSMS20009",
      "ATSMS20016",
      "ATSMS20018",
      "ATSMS20010",
      "ATSMS20017",
      "ATSMS00582",
      "ATSMS00627",
      "ATSMS00642",
      "ATSMS00914",
      "ATSMS00914 ",
      "ATSMS20015",
      "ATSMS20099",
      "ATSMS20100",
      "ATSMS20101",
      "ATSMS20102",
      "ATSMS20103",
      "ATSMS20104",
      "ATSMS20013",
      "ATSMS20019",
      "ATSMS20020",
      "ATSMS20021",
      "ATSMS20022",
      "ATBRS86205",
      "ATBRS86206",
      "ATBRS86207",
      "ATBRS86208",
      "ATBRS86209",
      "ATBRS86210",
      "ATBRS86211",
      "ATBRS86212",
      "ATBRS86213",
      "ATBRS86214",
      "ATBRS86215",
      "ATBRS86216",
      "ATSMS20007",
      "ATBRS86201",
      "ATBRS86202",
      "ATBRS86204",
      "ATBRS86203",
      "ATSMS20008",
      "ATSMS20011",
      "ATSMS20012",
      "ATSMS20023",
      "ATSMS20024",
      "ATSMS11009",
      "ATSMS11010",
      "ATSMS11006",
      "ATSMS11011",
      "TC003335"
    ],
    "usuario": {
      "id": 100,
      "nome": "Amaro José de Moura Filho",
      "login": "amaro.filho",
      "email": "amarofh@gmail.com",
      "senha": "0cf20ec50cb10f574c50811690939c5933e5def570649db774009515984155ad",
      "matricula": null,
      "instituicao": null,
      "adm": false,
      "ativo": true,
      "logado": true,
      "acessoSimultaneo": true,
      "remanejamento": false,
      "dtUltimoAcesso": "2021-10-19T12:22:13.231Z",
      "codigoRecuperacaoSenha": null,
      "perfilUsuario": {
        "id": 121,
        "nome": "STRANS",
        "ativo": true,
        "gerenciarLicenca": false,
        "visualizarImagensSemObliteracao": false,
        "sistema": null,
        "menus": null
      },
      "horario": null,
      "perfilDataServer": 0,
      "parentId": 0,
      "situacao": 0,
      "menus": [
        {
          "id": 19,
          "title": "Medição",
          "routerLink": "/app/relatorio/consolidacaodia",
          "href": null,
          "icon": null,
          "target": null,
          "hasSubMenu": false,
          "parentId": 18,
          "ordem": 1
        },
        {
          "id": 1,
          "title": "Home",
          "routerLink": "/app/paginainicial",
          "href": null,
          "icon": "home",
          "target": null,
          "hasSubMenu": false,
          "parentId": 0,
          "ordem": 1
        },
        {
          "id": 9,
          "title": "Radar",
          "routerLink": "/app/equipamento",
          "href": null,
          "icon": null,
          "target": null,
          "hasSubMenu": false,
          "parentId": 35,
          "ordem": 1
        },
        {
          "id": 41,
          "title": "Radar",
          "routerLink": "/app/mapa/radar",
          "href": null,
          "icon": null,
          "target": null,
          "hasSubMenu": false,
          "parentId": 7,
          "ordem": 1
        },
        {
          "id": 16,
          "title": "Fluxos",
          "routerLink": "/app/consulta/evento",
          "href": null,
          "icon": null,
          "target": null,
          "hasSubMenu": false,
          "parentId": 15,
          "ordem": 2
        },
        {
          "id": 34,
          "title": "Medição Por Faixa",
          "routerLink": "/app/relatorio/medicaofaixa",
          "href": null,
          "icon": null,
          "target": null,
          "hasSubMenu": false,
          "parentId": 18,
          "ordem": 2
        },
        {
          "id": 17,
          "title": "Infrações",
          "routerLink": "/app/consulta/infracao",
          "href": null,
          "icon": null,
          "target": null,
          "hasSubMenu": false,
          "parentId": 15,
          "ordem": 3
        },
        {
          "id": 15,
          "title": "Consulta",
          "routerLink": null,
          "href": null,
          "icon": "icon-search",
          "target": null,
          "hasSubMenu": true,
          "parentId": 0,
          "ordem": 3
        },
        {
          "id": 7,
          "title": "Mapa",
          "routerLink": null,
          "href": null,
          "icon": "map-o",
          "target": null,
          "hasSubMenu": true,
          "parentId": 0,
          "ordem": 5
        },
        {
          "id": 45,
          "title": "Engenharia",
          "routerLink": "/app/central3d/dashboard",
          "href": null,
          "icon": "bar-chart",
          "target": null,
          "hasSubMenu": false,
          "parentId": 0,
          "ordem": 7
        },
        {
          "id": 18,
          "title": "Relatório",
          "routerLink": null,
          "href": null,
          "icon": "icon-report",
          "target": null,
          "hasSubMenu": true,
          "parentId": 0,
          "ordem": 8
        }
      ],
      "contratos": [
        {
          "id": 2,
          "nome": "TERESINA",
          "descricao": "TERESINA",
          "estimativaValorMensal": 0,
          "estimativaValorTotal": 0,
          "dataInicial": 1559098800000,
          "dataFinal": 1559098800000,
          "latitude": "-4.904277731432103",
          "longitude": "-42.60179534827665",
          "zoom": 10,
          "ativo": true,
          "consolidarDados": true,
          "horaInicioConsolidacao": 2,
          "ipServerCentralProcess": null,
          "qtdDiasVencRegNaoMetro": 40,
          "qtdDiasVencAfericao": 40,
          "tempoVerifAlerta": 60,
          "envioSisgit": true,
          "tempoEnvioInfracaoSisgit": 60000,
          "tempoEnvioEventoSisgit": 60000,
          "timeOutEnvioSisgit": 120,
          "envioVideoSisgit": false,
          "urlWsSisgit": "http://172.10.1.165:8080/sisgit-ws/service?wsdl",
          "qtdEventosEnvioSisgit": 0,
          "qtdInfracoesEnvioSisgit": 100,
          "qtdDiasEnvioSisgit": 30,
          "dtInicioEnvioSisgit": "01/01/2017 08:40:09",
          "envioEventoValidoSisgit": true,
          "envioSpia": true,
          "envioAlerta": true,
          "envioAtAfv": false,
          "envioAtsmd2i": false,
          "envioLapisco": false,
          "urlEnvioLapisco": null,
          "urlEnvioAtsmd2i": null,
          "envioBiAtlanta": false,
          "urlEnvioBiAtlanta": null,
          "chaveEnvioBiAtlanta": null,
          "chaveWsAtsmd2i": null,
          "tempoEnvioSpia": 20000,
          "tempoConsultaSpia": 10,
          "tempoEnvioLapisco": 20000,
          "qtdEventosConsultaSpia": 400,
          "urlWsSpia": "https://wsocrspia.prf.gov.br/wsocrspia/pi",
          "usuarioSpia": "LABOR",
          "senhaSpia": "C08558B3E10008EFADAAA42839C2D0",
          "layoutSpia": "ATLLLLLF",
          "tempoEnvioInfracaoChegada": 1,
          "urlBi": "https://app.powerbi.com/view?r=eyJrIjoiODc4OWM2ZjQtODFmOC00NWVlLWI4NTMtMWEzNmQ1ODQ4NmFmIiwidCI6ImRhOWYxNTBmLWFjZDktNGRkYi04YjI1LTdiNGE2NzYzMjRiNSJ9&pageName=ReportSection70e00a36390c20002db1",
          "urlBiSeguranca": null,
          "urlBiCad": null,
          "situacao": 2,
          "nmCliente": "-",
          "imgLogoCliente": null,
          "pathLogo": "/dados/dataserver/anexos//contrato/2/2.png",
          "qtdDiasVencLicenca": 30,
          "tempoMaxVerifOffMin": 60,
          "tempoMaxVerifFluxoMin": 30,
          "tempoMaxVerifInfraMin": 60,
          "qtdDiasGeracaoLicenca": 365,
          "exportaArquivoFluxo": true,
          "envioArquivoFluxoFtp": false,
          "abrangencia": 2,
          "uf": "PI   ",
          "municipio": "Teresina",
          "gerarArquivoAnttAtivo": false,
          "custoMedioFaixa": 100,
          "codigosEnvioInfracaoAtsmsd2i": null,
          "qtdDiasEnvioAtsmd2i": 1,
          "equipamentos": null,
          "anexos": null
        }
      ],
      "usuarioLogado": null,
      "sistemas": [
        {
          "id": 1,
          "nome": "AT-CCO",
          "identificador": "cco",
          "chave": "3c0d3c39a68bf9b8553c773b587f8867",
          "ativo": true
        }
      ],
      "permissoesSistema": null
    }
  }